"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { MantineProvider, Image } from "@mantine/core";
import { AppShell, Navbar, Header, ActionIcon } from "@mantine/core";
import {
  HomeIcon,
  BellIcon,
  PlusIcon,
  DocumentPlusIcon,
} from "@heroicons/react/24/outline";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <Head>
            <title>Page title</title>
            <meta
              name="viewport"
              content="minimum-scale=1, initial-scale=1, width=device-width"
            />
          </Head>

          <MantineProvider
            withGlobalStyles
            withNormalizeCSS
            theme={{
              /** Put your mantine theme override here */
              colorScheme: "light",
            }}
          >
            <AppShell
              style={{
                backgroundColor: "",
                display: "flex",
                flex: 1,
                // margin: "10px",
                // padding: "10px",
                // height: "100%",
              }}
              padding="xs"
              navbar={
                <Navbar width={{ base: 65 }} style={{ alignItems: "center" }}>
                  <div
                    style={
                      {
                        // paddingLeft: "8px",
                        // paddingRight: "8px",
                        // backgroundColor: "red",
                        // alignItems: "center",
                        // justifyContent: "center",
                      }
                    }
                  >
                    <Image
                      //   className={}
                      src="./AWS_logo.svg"
                      // src="./cargill_logo.jpeg"
                      // src="./HERE_logo.png"
                      alt="logo"
                      fit="contain"
                      width={50}
                      height={50}
                      style={{
                        marginTop: "24px",
                        marginBottom: "48px",
                        alignSelf: "center",
                        // backgroundColor: "blue",
                      }}
                    />
                    <div
                      style={{
                        paddingLeft: "4px",
                      }}
                    >
                      <ActionIcon
                        variant="primary"
                        size="xl"
                        style={{ marginTop: "24px", backgroundColor: "" }}
                      >
                        <HomeIcon height={30} width={30} strokeWidth="1.5px" />
                      </ActionIcon>
                      <ActionIcon
                        variant="primary"
                        size="xl"
                        style={{ marginTop: "24px" }}
                      >
                        <BellIcon height={30} width={30} strokeWidth="1.5px" />
                      </ActionIcon>
                      <ActionIcon
                        variant="primary"
                        size="xl"
                        style={{ marginTop: "24px" }}
                      >
                        <DocumentPlusIcon
                          height={30}
                          width={30}
                          strokeWidth="1.5px"
                        />
                      </ActionIcon>
                    </div>
                  </div>
                </Navbar>
              }
              styles={(theme) => ({
                main: {
                  backgroundColor:
                    theme.colorScheme === "dark"
                      ? theme.colors.dark[8]
                      : theme.colors.gray[0],
                },
              })}
            >
              {/* Your application here */}
              {children}
            </AppShell>
          </MantineProvider>
        </>
      </body>
    </html>
  );
}
